/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{ts,tsx,js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Primary - Emerald Green palette
        primary: {
          DEFAULT: 'var(--color-primary)',
          50:  'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          950: 'var(--color-primary-950)',
        },
        // Secondary - Slate
        secondary: {
          DEFAULT: 'var(--color-secondary)',
          50:  'var(--color-secondary-50)',
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
          950: 'var(--color-secondary-950)',
        },
        // Semantic
        success: { DEFAULT: 'var(--color-success)', light: 'var(--color-success-light)', dark: 'var(--color-success-dark)' },
        warning: { DEFAULT: 'var(--color-warning)', light: 'var(--color-warning-light)', dark: 'var(--color-warning-dark)' },
        danger:  { DEFAULT: 'var(--color-danger)', light: 'var(--color-danger-light)', dark: 'var(--color-danger-dark)' },
        info:    { DEFAULT: 'var(--color-info)', light: 'var(--color-info-light)', dark: 'var(--color-info-dark)' },
        // Backgrounds
        bg: {
          DEFAULT: 'var(--color-bg)',
          card:    'var(--color-bg-card)',
          subtle:  'var(--color-bg-subtle)',
          muted:   'var(--color-bg-muted)',
        },
        // Text
        text: {
          DEFAULT: 'var(--color-text)',
          muted:   'var(--color-text-muted)',
          subtle:  'var(--color-text-subtle)',
        },
        // Borders
        border: {
          DEFAULT: 'var(--color-border)',
          light:   'var(--color-border-light)',
          strong:  'var(--color-border-strong)',
        },
      },
      fontFamily: {
        heading: ['Manrope', 'system-ui', 'sans-serif'],
        body:    ['Inter', 'system-ui', 'sans-serif'],
        mono:    ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        'display-2xl': ['4.5rem',  { lineHeight: '1.1',  letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-xl':  ['3.75rem', { lineHeight: '1.1',  letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg':  ['3rem',    { lineHeight: '1.15', letterSpacing: '-0.015em', fontWeight: '700' }],
        'display-md':  ['2.25rem', { lineHeight: '1.2',  letterSpacing: '-0.01em',  fontWeight: '700' }],
        'display-sm':  ['1.875rem',{ lineHeight: '1.25', letterSpacing: '-0.01em',  fontWeight: '700' }],
        'h1': ['2rem',    { lineHeight: '1.25', letterSpacing: '-0.015em', fontWeight: '700' }],
        'h2': ['1.5rem',  { lineHeight: '1.3',  letterSpacing: '-0.01em',  fontWeight: '600' }],
        'h3': ['1.25rem', { lineHeight: '1.4',  letterSpacing: '-0.005em', fontWeight: '600' }],
        'h4': ['1.125rem',{ lineHeight: '1.5',  fontWeight: '600' }],
        'h5': ['1rem',    { lineHeight: '1.5',  fontWeight: '600' }],
        'subtitle-lg': ['1.125rem', { lineHeight: '1.6', fontWeight: '400' }],
        'subtitle-md': ['1rem',     { lineHeight: '1.6', fontWeight: '400' }],
        'subtitle-sm': ['0.875rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['1.0625rem', { lineHeight: '1.7' }],
        'body-md': ['0.9375rem', { lineHeight: '1.7' }],
        'body-sm': ['0.875rem',  { lineHeight: '1.6' }],
        'caption':     ['0.75rem', { lineHeight: '1.5' }],
        'caption-xs':  ['0.6875rem', { lineHeight: '1.4' }],
      },
      spacing: {
        '0.5': '2px',
        '1':   '4px',
        '2':   '8px',
        '3':   '12px',
        '4':   '16px',
        '6':   '24px',
        '8':   '32px',
        '12':  '48px',
        '16':  '64px',
        '18':  '72px',
        '20':  '80px',
        '24':  '96px',
        '32':  '128px',
      },
      borderRadius: {
        'btn':    '12px',
        'input':  '12px',
        'card':   '20px',
        'dialog': '24px',
        'badge':  '999px',
        'sm':  '8px',
        'md':  '12px',
        'lg':  '16px',
        'xl':  '20px',
        '2xl': '24px',
        'full': '9999px',
      },
      boxShadow: {
        'card':    '0 1px 3px 0 rgba(0,0,0,0.05), 0 1px 2px -1px rgba(0,0,0,0.05)',
        'card-md': '0 4px 6px -1px rgba(0,0,0,0.05), 0 2px 4px -2px rgba(0,0,0,0.05)',
        'card-lg': '0 10px 15px -3px rgba(0,0,0,0.05), 0 4px 6px -4px rgba(0,0,0,0.04)',
        'card-hover': '0 8px 25px -5px rgba(0,0,0,0.1), 0 4px 10px -5px rgba(0,0,0,0.04)',
        'nav':     '0 1px 0 0 rgba(0,0,0,0.06)',
        'dialog':  '0 20px 60px -10px rgba(0,0,0,0.15)',
        'dropdown':'0 4px 20px -2px rgba(0,0,0,0.08)',
        'inner':   'inset 0 2px 4px 0 rgba(0,0,0,0.04)',
        'glow-primary': '0 0 0 3px rgba(16, 185, 129, 0.2)',
      },
      animation: {
        'shimmer':    'shimmer 1.5s infinite linear',
        'fade-in':    'fadeIn 0.2s ease-out',
        'slide-up':   'slideUp 0.25s ease-out',
        'slide-down': 'slideDown 0.25s ease-out',
        'scale-in':   'scaleIn 0.2s ease-out',
        'spin-slow':  'spin 2s linear infinite',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
        'bounce-soft':'bounceSoft 1s ease-in-out infinite',
        'counter':    'counter 1s ease-out forwards',
        'progress':   'progress 1.2s ease-in-out forwards',
      },
      keyframes: {
        shimmer: {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition:  '200% 0' },
        },
        fadeIn:    { from: { opacity: '0' },                       to: { opacity: '1' } },
        slideUp:   { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideDown: { from: { opacity: '0', transform: 'translateY(-8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:   { from: { opacity: '0', transform: 'scale(0.96)' }, to: { opacity: '1', transform: 'scale(1)' } },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '0.6' },
        },
        bounceSoft: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%':      { transform: 'translateY(-4px)' },
        },
        progress: {
          from: { width: '0%' },
          to:   { width: 'var(--progress-width, 70%)' },
        },
      },
      maxWidth: {
        'content': '1280px',
        'prose':   '680px',
      },
      transitionDuration: {
        '150': '150ms',
        '200': '200ms',
        '300': '300ms',
        '500': '500ms',
      },
      transitionTimingFunction: {
        'spring':     'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'ease-smooth':'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      zIndex: {
        'sidebar':  '40',
        'navbar':   '50',
        'dropdown': '60',
        'drawer':   '70',
        'modal':    '80',
        'toast':    '90',
        'tooltip':  '100',
      },
    },
  },
  plugins: [],
}
